name: Enable RDP to Windows Runner

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    steps:
      - name: Download and extract ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath ngrok
          Move-Item ngrok\ngrok.exe $env:USERPROFILE\ngrok.exe

      - name: Authenticate ngrok
        run: |
          $NGROK_AUTH_TOKEN = "${{ secrets.NGROK_AUTH_TOKEN }}"
          & "$env:USERPROFILE\ngrok.exe" authtoken $NGROK_AUTH_TOKEN

      - name: Enable RDP Access
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start ngrok TCP tunnel
        run: Start-Process -NoNewWindow -FilePath "$env:USERPROFILE\ngrok.exe" -ArgumentList "tcp 3389"

      - name: Wait and get tunnel info
        run: |
          Start-Sleep -Seconds 10
          Invoke-WebRequest http://127.0.0.1:4040/api/tunnels > tunnels.json
          Get-Content tunnels.json

      - name: Show ngrok tunnel address
        run: |
          $response = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
          $tcpAddr = $response.tunnels[0].public_url -replace "tcp://", ""
          Write-Host "RDP address: $tcpAddr"
