- name: Start ngrok tunnel and show raw output
  shell: powershell
  run: |
    Write-Host "`n🔌 Starting ngrok...`n"
    
    # Start ngrok and capture ALL output (stdout + stderr)
    & "$env:USERPROFILE\ngrok.exe" tcp 3389 *>&1 | Tee-Object ngrok_full.log

    # Print full output for inspection
    Write-Host "`n📄 ngrok full output:"
    Get-Content ngrok_full.log

    # Try to extract the public TCP address
    $log = Get-Content ngrok_full.log -Raw
    if ($log -match "tcp://[^\s]+") {
      $tcp = $matches[0] -replace "tcp://", ""
      Write-Host "`n✅ RDP Address: $tcp"
      Write-Host "Username: runneradmin"
      Write-Host "Password: MySecureP@ssw0rd!"
    } else {
      throw "❌ ngrok did not start a TCP tunnel. See log above."
    }
