name: RDP via Serveo

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:
      - name: Enable RDP & Set Password
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin MySecureP@ssw0rd!

      - name: Start Serveo SSH Tunnel
        run: |
          Start-Process -NoNewWindow ssh.exe -ArgumentList "-R 0:localhost:3389 serveo.net -o StrictHostKeyChecking=no" -RedirectStandardOutput serveo.log
          Start-Sleep -Seconds 10

      - name: Get Serveo Tunnel Info
        run: |
          $log = Get-Content serveo.log -Raw
          Write-Host "`n📡 Serveo Output:`n$log"

          if ($log -match "Forwarding TCP from (.+?)\s") {
            $addr = $matches[1]
            Write-Host "`n✅ RDP Address: $addr"
            Write-Host "Username: runneradmin"
            Write-Host "Password: MySecureP@ssw0rd!"
          } else {
            throw "❌ Could not find Serveo tunnel. Check logs above."
          }
